/**
 * generate_long_content — Structures long-form content: blog posts, newsletters, articles.
 * Returns markdown with SEO metadata.
 */
import { Tool } from '../base-agent';

interface ContentSection {
    heading: string;
    content: string;
}

export function createGenerateLongContentTool(): Tool {
    return {
        name: 'generate_long_content',
        description: 'Generate structured long-form content (blog posts, newsletters, articles) with SEO metadata and markdown formatting.',
        parameters: {
            topic: { type: 'string', description: 'The main topic for the content', required: true },
            format: { type: 'string', description: 'Content format: blog, newsletter, article (default: blog)', required: false },
            wordCount: { type: 'number', description: 'Target word count (default: 1500)', required: false },
            outline: { type: 'array', description: 'Array of section headings to structure the content', required: false },
            sections: { type: 'array', description: 'Array of { heading, content } objects (if LLM has already drafted)', required: false },
            metaDescription: { type: 'string', description: 'SEO meta description', required: false },
        },
        execute: async (args: Record<string, unknown>): Promise<string> => {
            const topic = args.topic as string;
            const format = (args.format as string) || 'blog';
            const wordCount = (args.wordCount as number) || 1500;
            const outline = (args.outline as string[]) || [];
            const sections = (args.sections as ContentSection[]) || [];
            const metaDescription = args.metaDescription as string | undefined;

            if (!topic || topic.trim().length === 0) {
                return JSON.stringify({ error: 'Topic is required' });
            }

            // If sections are provided (LLM already drafted), compile into markdown
            if (sections.length > 0) {
                const lines: string[] = [];
                lines.push(`# ${topic}`);
                lines.push('');
                lines.push(`*Generated by The Content Machine — ${new Date().toISOString().split('T')[0]}*`);
                lines.push('');

                if (metaDescription) {
                    lines.push(`> **Meta Description:** ${metaDescription}`);
                    lines.push('');
                }

                lines.push('---');
                lines.push('');

                for (const section of sections) {
                    lines.push(`## ${section.heading}`);
                    lines.push('');
                    lines.push(section.content);
                    lines.push('');
                }

                lines.push('---');
                lines.push('');
                lines.push('*Generated by The Content Machine — an AI content agent powered by MultiversX.*');

                const markdown = lines.join('\n');
                const actualWordCount = markdown.split(/\s+/).length;

                return JSON.stringify({
                    topic,
                    format,
                    sectionCount: sections.length,
                    wordCount: actualWordCount,
                    targetWordCount: wordCount,
                    markdown,
                    seo: {
                        title: topic,
                        metaDescription: metaDescription || `${topic} — comprehensive guide`,
                        headings: sections.map(s => s.heading),
                    },
                });
            }

            // If no sections, return a structured brief for the LLM
            const defaultOutline = outline.length > 0 ? outline : [
                'Introduction',
                'The Problem',
                'The Solution',
                'Key Takeaways',
                'Conclusion',
            ];

            return JSON.stringify({
                topic,
                format,
                targetWordCount: wordCount,
                outline: defaultOutline,
                instruction: `Write a ${format} about "${topic}" with ~${wordCount} words. Structure it with the provided outline. Include a compelling introduction and actionable conclusion.`,
                seoGuidelines: {
                    includeMetaDescription: true,
                    useH2ForSections: true,
                    targetKeyword: topic.toLowerCase(),
                },
            });
        },
    };
}
