/**
 * generate_report — Synthesizes research data into a structured markdown report.
 */
import { Tool } from '../base-agent';

export function createGenerateReportTool(): Tool {
    return {
        name: 'generate_report',
        description: 'Generate a structured markdown research report from collected data and findings.',
        parameters: {
            title: { type: 'string', description: 'Report title', required: true },
            sections: { type: 'array', description: 'Array of { heading, content } objects', required: true },
            summary: { type: 'string', description: 'Executive summary', required: false },
        },
        execute: async (args: Record<string, unknown>): Promise<string> => {
            const title = (args.title as string) || 'Research Report';
            const sections = (args.sections as Array<{ heading: string; content: string }>) || [];
            const summary = args.summary as string;

            const lines: string[] = [];

            lines.push(`# ${title}`);
            lines.push('');
            lines.push(`*Generated by OpenClaw Research Agent — ${new Date().toISOString().split('T')[0]}*`);
            lines.push('');

            if (summary) {
                lines.push('## Executive Summary');
                lines.push('');
                lines.push(summary);
                lines.push('');
            }

            lines.push('---');
            lines.push('');

            for (const section of sections) {
                lines.push(`## ${section.heading}`);
                lines.push('');
                lines.push(section.content);
                lines.push('');
            }

            lines.push('---');
            lines.push('');
            lines.push('*This report was generated by an AI research agent with on-chain proof of authenticity on MultiversX.*');

            const report = lines.join('\n');

            return JSON.stringify({
                title,
                sectionCount: sections.length,
                wordCount: report.split(/\s+/).length,
                markdown: report,
            });
        },
    };
}
