/**
 * generate_video_script — Produces video scripts with hook, body, CTA sections.
 * Structured with timestamps and speaker notes.
 */
import { Tool } from '../base-agent';

interface ScriptSection {
    timestamp: string;
    section: string;
    content: string;
    speakerNotes?: string;
}

export function createGenerateVideoScriptTool(): Tool {
    return {
        name: 'generate_video_script',
        description: 'Generate a video script with hook, body, and CTA sections. Includes timestamps and speaker notes.',
        parameters: {
            topic: { type: 'string', description: 'The topic for the video', required: true },
            duration: { type: 'number', description: 'Target duration in minutes (default: 5)', required: false },
            style: { type: 'string', description: 'Style: educational, storytelling, listicle, review (default: educational)', required: false },
            sections: { type: 'array', description: 'Array of { timestamp, section, content, speakerNotes } (if LLM has already drafted)', required: false },
        },
        execute: async (args: Record<string, unknown>): Promise<string> => {
            const topic = args.topic as string;
            const duration = (args.duration as number) || 5;
            const style = (args.style as string) || 'educational';
            const sections = (args.sections as ScriptSection[]) || [];

            if (!topic || topic.trim().length === 0) {
                return JSON.stringify({ error: 'Topic is required' });
            }

            // If sections are provided, compile into a formatted script
            if (sections.length > 0) {
                const lines: string[] = [];
                lines.push(`# VIDEO SCRIPT: ${topic}`);
                lines.push(`**Duration:** ~${duration} minutes | **Style:** ${style}`);
                lines.push(`**Generated:** ${new Date().toISOString().split('T')[0]}`);
                lines.push('');
                lines.push('---');
                lines.push('');

                for (const section of sections) {
                    lines.push(`### [${section.timestamp}] ${section.section}`);
                    lines.push('');
                    lines.push(section.content);
                    if (section.speakerNotes) {
                        lines.push('');
                        lines.push(`> 🎬 **Speaker Notes:** ${section.speakerNotes}`);
                    }
                    lines.push('');
                }

                lines.push('---');
                lines.push('*Script generated by The Content Machine.*');

                const script = lines.join('\n');
                const wordCount = script.split(/\s+/).length;
                const estimatedMinutes = Math.round(wordCount / 150); // ~150 words/min speaking rate

                return JSON.stringify({
                    topic,
                    style,
                    sectionCount: sections.length,
                    wordCount,
                    estimatedDuration: `${estimatedMinutes} minutes`,
                    targetDuration: `${duration} minutes`,
                    script,
                });
            }

            // Return a structured template for the LLM to fill
            const template: ScriptSection[] = [
                { timestamp: '0:00', section: 'HOOK', content: '', speakerNotes: 'Grab attention in first 5 seconds. Bold claim or question.' },
                { timestamp: '0:15', section: 'INTRO', content: '', speakerNotes: 'Introduce yourself and the topic. Set expectations.' },
                { timestamp: '0:45', section: 'MAIN CONTENT', content: '', speakerNotes: 'Core value. 2-3 key points with examples.' },
                { timestamp: `${Math.floor(duration * 0.7)}:00`, section: 'RECAP', content: '', speakerNotes: 'Summarize key takeaways.' },
                { timestamp: `${Math.floor(duration * 0.85)}:00`, section: 'CTA', content: '', speakerNotes: 'Call to action: subscribe, comment, share, link in bio.' },
            ];

            return JSON.stringify({
                topic,
                style,
                targetDuration: `${duration} minutes`,
                targetWordCount: duration * 150,
                template,
                instruction: `Write a ${style}-style video script about "${topic}" lasting ~${duration} minutes. Use the template sections. Include speaker notes for delivery guidance.`,
            });
        },
    };
}
