#!/bin/bash
set -euo pipefail

# ============================================
# mx-openclaw-template-solution: Setup Wizard
# ============================================
# Interactive CLI wizard that configures your bot.
# Generates: .env, agent.config.json, wallet.pem
# ============================================

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "🤖 mx-openclaw-template-solution — Setup Wizard"
echo "================================================"
echo ""

# 1. Bot Name
read -p "📛 Bot name (e.g., crypto-research-pro): " BOT_NAME
BOT_NAME="${BOT_NAME:-my-openclaw-bot}"

# 2. Description
read -p "📝 Short description: " BOT_DESC
BOT_DESC="${BOT_DESC:-A MultiversX-powered AI agent}"

# 3. Price per query
read -p "💰 Price per query in USDC (e.g., 0.50): " PRICE
PRICE="${PRICE:-0.50}"

# 4. LLM Provider
echo ""
echo "🧠 LLM Provider:"
echo "   1) OpenAI (gpt-4o)"
echo "   2) Anthropic (claude-sonnet)"
echo "   3) Google (gemini-2.5-pro)"
read -p "   Choose [1-3]: " LLM_CHOICE

case "${LLM_CHOICE:-1}" in
  1) LLM_PROVIDER="openai"; LLM_MODEL="gpt-4o" ;;
  2) LLM_PROVIDER="anthropic"; LLM_MODEL="claude-sonnet-4-20250514" ;;
  3) LLM_PROVIDER="google"; LLM_MODEL="gemini-2.5-pro" ;;
  *) LLM_PROVIDER="openai"; LLM_MODEL="gpt-4o" ;;
esac

# 5. API Key
read -p "🔑 $LLM_PROVIDER API Key: " LLM_API_KEY

# 6. Network
echo ""
echo "🌐 Network:"
echo "   1) Devnet (testing)"
echo "   2) Mainnet (production)"
read -p "   Choose [1-2]: " NETWORK_CHOICE

case "${NETWORK_CHOICE:-1}" in
  1)
    CHAIN_ID="D"
    API_URL="https://devnet-api.multiversx.com"
    EXPLORER_URL="https://devnet-explorer.multiversx.com"
    ;;
  2)
    CHAIN_ID="1"
    API_URL="https://api.multiversx.com"
    EXPLORER_URL="https://explorer.multiversx.com"
    ;;
  *)
    CHAIN_ID="D"
    API_URL="https://devnet-api.multiversx.com"
    EXPLORER_URL="https://devnet-explorer.multiversx.com"
    ;;
esac

# 7. Generate wallet
echo ""
echo "🔐 Generating wallet..."
cd "$ROOT_DIR"
if [ ! -f wallet.pem ]; then
  npx ts-node scripts/generate_wallet.ts
  echo "   ✅ wallet.pem created"
else
  echo "   ℹ️  wallet.pem already exists, skipping"
fi

# 8. Write .env
echo ""
echo "📄 Writing .env..."
cat > "$ROOT_DIR/.env" << EOF
# Generated by setup wizard — $(date)
MULTIVERSX_CHAIN_ID=$CHAIN_ID
MULTIVERSX_API_URL=$API_URL
MULTIVERSX_EXPLORER_URL=$EXPLORER_URL
MULTIVERSX_PRIVATE_KEY=./wallet.pem

IDENTITY_REGISTRY_ADDRESS=erd1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6gq4hu
VALIDATION_REGISTRY_ADDRESS=erd1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6gq4hu
REPUTATION_REGISTRY_ADDRESS=erd1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6gq4hu
ESCROW_CONTRACT_ADDRESS=erd1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6gq4hu

X402_FACILITATOR_URL=http://localhost:4000
MULTIVERSX_RELAYER_URL=http://localhost:3001
MULTIVERSX_MCP_URL=http://localhost:3000

AGENT_NAME=$BOT_NAME
AGENT_URI=https://$BOT_NAME.example.com

LLM_PROVIDER=$LLM_PROVIDER
LLM_API_KEY=$LLM_API_KEY
LLM_MODEL=$LLM_MODEL

PRICE_PER_QUERY=$PRICE
PRICE_TOKEN=USDC-350c4e

BACKEND_PORT=4000
FRONTEND_PORT=3000
CORS_ORIGIN=http://localhost:3000
EOF
echo "   ✅ .env created"

# 9. Write agent.config.json
echo "📄 Writing agent.config.json..."
cat > "$ROOT_DIR/agent.config.json" << EOF
{
  "agentName": "$BOT_NAME",
  "description": "$BOT_DESC",
  "version": "1.0.0",
  "nonce": 0,
  "network": "$([ "$CHAIN_ID" = "D" ] && echo "devnet" || echo "mainnet")",
  "pricing": {
    "perQuery": "$PRICE",
    "token": "USDC-350c4e"
  },
  "llm": {
    "provider": "$LLM_PROVIDER",
    "model": "$LLM_MODEL"
  },
  "services": [
    {
      "id": "default",
      "name": "General Query",
      "description": "Process a text query and return a structured response",
      "pricePerCall": "$PRICE",
      "token": "USDC-350c4e"
    }
  ]
}
EOF
echo "   ✅ agent.config.json created"

echo ""
echo "============================================"
echo "✅ Setup complete!"
echo "============================================"
echo ""
echo "Next steps:"
if [ "$CHAIN_ID" = "D" ]; then
  echo "  1. Fund your wallet:  npm run fund"
fi
echo "  2. Register on-chain: npm run register"
echo "  3. Start locally:     npm run dev"
echo "  4. Deploy to VPS:     npm run provision -- root@IP"
echo "                        npm run deploy -- moltbot@IP yourdomain.com"
